set(${REPOSITORY_NAME}_VERSION 0.5)
set(${REPOSITORY_NAME}_MAJOR_VERSION 00)
set(${REPOSITORY_NAME}_MAJOR_MINOR_VERSION 000500)
set(${REPOSITORY_NAME}_VERSION_STRING "0.5")
set(${REPOSITORY_NAME}_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
